openapi: '3.1.0'
info:
  title: toastmasters-api
  description: An API that retrieve public information from the Toastmasters website
  version: '1.0.0'
servers:
  - url: http://localhost:3000/api/v1
    description: The localhost url
tags:
  - name: Pathway API
    description: Pathway endpoints
components:
  schemas:
    Project:
      type: object
      properties:
        name:
          type: string
          description: The project's name
          example: Ice Breaker
        elective:
          type: boolean
          description: Flag to indicate if a project is mandatory or elective
          example: false
        order:
          type: integer
          description: The order of a project, used when project is mandatory only
          example: 1
    Level:
      type: object
      properties:
        name:
          type: string
          description: The level's name
          example: Mastering Fundamentals
        levelNumber:
          type: integer
          description: The level's number
          example: 1
        numberOfProjects:
          type: integer
          description: The total number of projects to consider this level as completed (including the mandatory and elective projects)
          example: 4
        projects:
          type: array
          items:
            $ref: '#/components/schemas/Project'
    Path:
      type: object
      properties:
        name:
          type: string
          description: The pathway's name
          example: Dynamic Leadership
        levels:
          type: array
          items:
            $ref: '#/components/schemas/Level'
    Error:
      type: object
      properties:
        message:
          type: string
          description: The error message
          example: The path X does not exist
paths:
  /paths:
    get:
      tags:
        - Pathway API
      summary: Get all pathways
      description: Get all pathways each with their information of levels and projects
      operationId: findAllPaths
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Path'
  /paths/{name}:
    get:
      tags:
        - Pathway API
      summary: Get pathway by name
      description: Get the pathway information of the specified name with all of its levels and projects
      operationId: findPathByName
      parameters:
        - name: name
          in: path
          description: The pathway name to find
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Path'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
