openapi: '3.1.0'
info:
  title: toastmasters-api
  description: An API that retrieve public information from the Toastmasters website
  version: '1.0.0'
servers:
  - url: http://localhost:3000/api/v1
    description: The localhost url
tags:
  - name: Pathway API
    description: Pathway endpoints
  - name: Role API
    description: Role endpoints
  - name: Cabinet Role API
    description: Cabinet role endpoints
components:
  schemas:
    Project:
      type: object
      properties:
        name:
          type: string
          description: The project's name
          example: Ice Breaker
        elective:
          type: boolean
          description: Flag to indicate if a project is mandatory or elective
          example: false
        order:
          type: integer
          description: The order of a project, used when project is mandatory only
          example: 1
    Level:
      type: object
      properties:
        name:
          type: string
          description: The level's name
          example: Mastering Fundamentals
        levelNumber:
          type: integer
          description: The level's number
          example: 1
        numberOfProjects:
          type: integer
          description: The total number of projects to consider this level as completed (including the mandatory and elective projects)
          example: 4
        projects:
          type: array
          items:
            $ref: '#/components/schemas/Project'
    Path:
      type: object
      properties:
        name:
          type: string
          description: The pathway's name
          example: Dynamic Leadership
        levels:
          type: array
          items:
            $ref: '#/components/schemas/Level'
    Role:
      type: object
      properties:
        name:
          type: string
          description: The role's name
          example: Toastmaster of the Evening
        abbreviation:
          type: string
          description: The role's abbreviation
          example: TME
    CabinetRole:
      type: object
      properties:
        name:
          type: string
          description: The cabinet role's name
          example: Vice President of Education
        abbreviation:
          type: string
          description: The cabinet role's abbreviation
          example: VPE
    Status:
      type: object
      properties:
        status:
          type: string
          description: The status of the operation
          example: success
    Error:
      type: object
      properties:
        message:
          type: string
          description: The error message
          example: The path X does not exist
paths:
  /paths:
    get:
      tags:
        - Pathway API
      summary: Get all pathways
      description: Get all pathways each with their information of levels and projects
      operationId: findAllPaths
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Path'
  /paths/update:
    post:
      tags:
        - Pathway API
      summary: Update the pathways
      description: Update the pathways from the official Toastmasters website
      operationId: updatePaths
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
  /paths/{name}:
    get:
      tags:
        - Pathway API
      summary: Get pathway by name
      description: Get the pathway information of the specified name with all of its levels and projects
      operationId: findPathByName
      parameters:
        - name: name
          in: path
          description: The pathway name to find
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Path'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /roles:
    get:
      tags:
        - Role API
      summary: Get all roles
      description: Get all roles that can be present in a roster
      operationId: findAllRoles
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Role'
  /roles/update:
    post:
      tags:
        - Role API
      summary: Update the roles
      description: Update the roles with updated values
      operationId: updateRoles
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
  /cabinet-roles:
    get:
      tags:
        - Cabinet Role API
      summary: Get all cabinet roles
      description: Get all cabinet roles that can be present in a cabinet
      operationId: findAllCabinetRoles
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CabinetRole'
  /cabinet-roles/update:
    post:
      tags:
        - Cabinet Role API
      summary: Update the cabinet roles
      description: Update the cabinet roles with updated values
      operationId: updateCabinetRoles
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
